import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  panel: {
    position: 'absolute',
    left: 12,
    right: 12,
    bottom: 14,
    borderRadius: 28,
    backgroundColor: '#ffffff',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 14,
    gap: 12,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: -8 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 16,
  },
  panelCollapsed: {
    borderRadius: 22,
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 10,
    gap: 8,
  },
  panelHandleButton: {
    alignItems: 'center',
    gap: 6,
  },
  handle: {
    alignSelf: 'center',
    width: 72,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#e5e7eb',
  },
  panelHandleLabelRow: {
    minHeight: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  panelHandleLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#94a3b8',
  },
  collapsedPanelRow: {
    minHeight: 48,
    alignSelf: 'stretch',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  collapsedIconWrap: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#ecfdf5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  collapsedTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  collapsedEyebrow: {
    fontSize: 11,
    fontWeight: '900',
    color: '#10b981',
    textTransform: 'uppercase',
  },
  collapsedRouteLabel: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0f172a',
  },
  collapsedMetricBlock: {
    minWidth: 60,
    alignItems: 'flex-end',
  },
  collapsedMetricValue: {
    fontSize: 13,
    fontWeight: '900',
    color: '#0f172a',
  },
  collapsedMetricLabel: {
    fontSize: 10,
    fontWeight: '900',
    color: '#94a3b8',
  },
  filterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  filterButton: {
    flex: 1,
    minHeight: 38,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d1fae5',
    backgroundColor: '#ecfdf5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  filterButtonActive: {
    backgroundColor: '#10b981',
    borderColor: '#10b981',
  },
  filterButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#10b981',
  },
  filterButtonTextActive: {
    color: '#ffffff',
  },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  routeIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: '#10b981',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  eyebrow: {
    fontSize: 12,
    fontWeight: '900',
    color: '#94a3b8',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  routeLabel: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0f172a',
  },
  headerActions: {
    alignItems: 'flex-end',
    gap: 6,
  },
  availabilityPill: {
    minHeight: 30,
    borderRadius: 10,
    paddingHorizontal: 12,
    backgroundColor: '#8ee0bf',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
  },
  availabilityPillMuted: {
    backgroundColor: '#e2e8f0',
  },
  availabilityDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#10b981',
  },
  availabilityDotMuted: {
    backgroundColor: '#94a3b8',
  },
  availabilityText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#ffffff',
  },
  availabilityTextMuted: {
    color: '#64748b',
  },
  metricGrid: {
    minHeight: 64,
    borderRadius: 10,
    backgroundColor: '#e7e7e7',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  metricItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  metricDivider: {
    width: 1,
    alignSelf: 'stretch',
    backgroundColor: '#d4d4d4',
  },
  metricValue: {
    fontSize: 11,
    fontWeight: '900',
    color: '#7bd3a8',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  statusText: {
    flex: 1,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: '#64748b',
  },
  countText: {
    minWidth: 42,
    textAlign: 'right',
    fontSize: 12,
    fontWeight: '900',
    color: '#10b981',
  },
  fareCard: {
    minHeight: 82,
    borderRadius: 8,
    backgroundColor: '#10b981',
    paddingHorizontal: 18,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  fareTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  fareLabel: {
    fontSize: 12,
    fontWeight: '900',
    color: '#d1fae5',
  },
  fareAmount: {
    fontSize: 19,
    fontWeight: '900',
    color: '#ffffff',
  },
  fareToggleRow: {
    flexDirection: 'row',
    gap: 8,
  },
  fareToggle: {
    minHeight: 38,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ffffff',
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fareToggleActive: {
    backgroundColor: '#ffffff',
  },
  fareToggleText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#ffffff',
  },
  fareToggleTextActive: {
    color: '#10b981',
  },
});
