import { StyleSheet } from 'react-native';

export const commuterStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0f172a',
  },
  map: {
    flex: 1,
  },
  searchOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 50,
    backgroundColor: '#ffffff',
    borderBottomLeftRadius: 24,
    borderBottomRightRadius: 24,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 20,
    elevation: 10,
    paddingTop: 54,
    paddingBottom: 12,
  },
  searchOverlayInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 14,
    marginBottom: 6,
    borderBottomWidth: 1,
    borderBottomColor: '#e2e8f0',
    paddingBottom: 10,
  },
  searchOverlayInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#0f172a',
    paddingVertical: 6,
  },
  searchOverlayIcon: {
    paddingLeft: 10,
  },
  searchRouteList: {
    maxHeight: 260,
  },
  searchRouteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  searchRouteItemText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#0f172a',
  },
  searchRouteEmpty: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  searchRouteEmptyText: {
    fontSize: 14,
    color: '#94a3b8',
  },
  topBarRow: {
    position: 'absolute',
    top: 54,
    left: 14,
    right: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    zIndex: 10,
  },
  iconButton: {
    width: 52,
    height: 52,
    borderRadius: 18,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 12,
    right: 13,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#10b981',
    borderWidth: 1.5,
    borderColor: '#ffffff',
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 24,
    paddingHorizontal: 16,
    paddingVertical: 13,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  searchBarSelected: {
    backgroundColor: '#10b981',
    borderColor: '#10b981',
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    textAlign: 'center',
  },
  searchInputPlaceholder: {
    color: '#94a3b8',
  },
  searchInputSelected: {
    color: '#ffffff',
  },
  manualReferenceCrosshair: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    marginLeft: -21,
    marginTop: -42,
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 2,
    borderColor: '#10b981',
    backgroundColor: 'rgba(255,255,255,0.96)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 9,
  },
  manualReferencePointer: {
    position: 'absolute',
    bottom: -10,
    width: 2,
    height: 12,
    borderRadius: 1,
    backgroundColor: '#10b981',
  },
  manualReferenceBar: {
    position: 'absolute',
    left: 14,
    right: 14,
    bottom: 20,
    borderRadius: 22,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
    elevation: 16,
    zIndex: 12,
  },
  manualReferenceTextBlock: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  manualReferenceEyebrow: {
    fontSize: 11,
    fontWeight: '900',
    color: '#10b981',
    textTransform: 'uppercase',
  },
  manualReferenceTitle: {
    fontSize: 13,
    fontWeight: '800',
    color: '#0f172a',
  },
  manualReferenceButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  manualReferenceButton: {
    minHeight: 38,
    borderRadius: 14,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  manualReferenceButtonGhost: {
    borderColor: '#cbd5e1',
    backgroundColor: '#ffffff',
  },
  manualReferenceButtonPrimary: {
    borderColor: '#10b981',
    backgroundColor: '#10b981',
  },
  manualReferenceButtonDisabled: {
    borderColor: '#e2e8f0',
    backgroundColor: '#f8fafc',
  },
  manualReferenceButtonText: {
    fontSize: 12,
    fontWeight: '800',
  },
  manualReferenceButtonTextGhost: {
    color: '#64748b',
  },
  manualReferenceButtonTextPrimary: {
    color: '#ffffff',
  },
  manualReferenceButtonTextDisabled: {
    color: '#94a3b8',
  },
  mapVehicleButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  mapVehicleButtonBus: {},
  mapVehicleButtonJeep: {},
  mapVehicleButtonActive: {
    transform: [{ scale: 1.05 }],
  },
});
